// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-services.ts
var list_services_default = defineTool({
  name: "list_services",
  title: "Listar servicios y precios",
  description: "Lista los servicios activos de Nave Studio (criomedicina, yoga, breathwork) con precio en CLP, duraci\xF3n y capacidad m\xE1xima.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("services").select("id, name, description, price_clp, duration_minutes, max_capacity, color_tag, is_trial_enabled").eq("is_active", true).order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-weekly-schedule.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var DAYS = ["Domingo", "Lunes", "Martes", "Mi\xE9rcoles", "Jueves", "Viernes", "S\xE1bado"];
var list_weekly_schedule_default = defineTool2({
  name: "list_weekly_schedule",
  title: "Horario semanal",
  description: "Horario semanal recurrente publicado en /horarios: d\xEDa, hora de inicio, clase e instructor. Opcionalmente filtra por d\xEDa de la semana (0=Domingo).",
  inputSchema: {
    day_of_week: z.number().int().min(0).max(6).optional().describe("Filtro opcional de d\xEDa de la semana, 0=Domingo \u2026 6=S\xE1bado.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ day_of_week }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("schedule_entries").select("day_of_week, start_time, display_name, badges, professional_id, service_id, sort_order").eq("is_active", true).order("day_of_week", { ascending: true }).order("start_time", { ascending: true });
    if (typeof day_of_week === "number") query = query.eq("day_of_week", day_of_week);
    const [{ data: entries, error }, { data: services }, { data: professionals }] = await Promise.all([
      query,
      supabase.from("services").select("id, name").eq("is_active", true),
      supabase.rpc("get_active_professionals")
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const serviceName = new Map((services ?? []).map((s) => [s.id, s.name]));
    const proName = new Map(
      (professionals ?? []).map((p) => [p.id, p.name])
    );
    const schedule = (entries ?? []).map((e) => ({
      day: DAYS[e.day_of_week] ?? String(e.day_of_week),
      day_of_week: e.day_of_week,
      start_time: String(e.start_time).slice(0, 5),
      class_name: e.display_name ?? serviceName.get(e.service_id) ?? "Clase",
      instructor: e.professional_id ? proName.get(e.professional_id) ?? null : null,
      badges: e.badges ?? []
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(schedule, null, 2) }],
      structuredContent: { schedule }
    };
  }
});

// src/lib/mcp/tools/list-available-slots.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_available_slots_default = defineTool3({
  name: "list_available_slots",
  title: "Cupos disponibles",
  description: "Lista los horarios reservables con cupo disponible en un rango de fechas (m\xE1x. 30 d\xEDas), con clase, instructor y cupos restantes.",
  inputSchema: {
    date_from: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha inicial YYYY-MM-DD."),
    date_to: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha final YYYY-MM-DD (inclusive)."),
    service_id: z2.string().uuid().optional().describe("Filtro opcional por servicio.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_from, date_to, service_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("generated_slots").select("id, date_time_start, date_time_end, max_capacity, confirmed_bookings, service_id, professional_id").eq("is_active", true).gte("date_time_start", `${date_from}T00:00:00`).lte("date_time_start", `${date_to}T23:59:59`).order("date_time_start", { ascending: true }).limit(500);
    if (service_id) query = query.eq("service_id", service_id);
    const [{ data: slots, error }, { data: services }, { data: professionals }] = await Promise.all([
      query,
      supabase.from("services").select("id, name, price_clp").eq("is_active", true),
      supabase.rpc("get_active_professionals")
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const svc = new Map(
      (services ?? []).map((s) => [s.id, s])
    );
    const proName = new Map(
      (professionals ?? []).map((p) => [p.id, p.name])
    );
    const available = (slots ?? []).filter((s) => s.confirmed_bookings < s.max_capacity).map((s) => ({
      slot_id: s.id,
      starts_at: s.date_time_start,
      ends_at: s.date_time_end,
      class_name: svc.get(s.service_id)?.name ?? null,
      price_clp: svc.get(s.service_id)?.price_clp ?? null,
      instructor: proName.get(s.professional_id) ?? null,
      spots_left: s.max_capacity - s.confirmed_bookings
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(available, null, 2) }],
      structuredContent: { slots: available, count: available.length }
    };
  }
});

// src/lib/mcp/tools/list-bookings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_bookings_default = defineTool4({
  name: "list_bookings",
  title: "Listar reservas",
  description: "Lista reservas en un rango de fechas con cliente, clase, estado y monto pagado. Solo devuelve datos si la cuenta conectada tiene permisos de administrador.",
  inputSchema: {
    date_from: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha inicial YYYY-MM-DD."),
    date_to: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha final YYYY-MM-DD (inclusive)."),
    status: z3.string().optional().describe("Filtro opcional de estado, por ejemplo 'confirmed' o 'cancelled'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_from, date_to, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select(
      "id, customer_name, customer_email, customer_phone, status, date_time_start, date_time_end, final_price, service_id, professional_id"
    ).gte("date_time_start", `${date_from}T00:00:00`).lte("date_time_start", `${date_to}T23:59:59`).order("date_time_start", { ascending: true }).limit(500);
    if (status) query = query.eq("status", status);
    const [{ data: bookings, error }, { data: services }] = await Promise.all([
      query,
      supabase.from("services").select("id, name").eq("is_active", true)
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const serviceName = new Map((services ?? []).map((s) => [s.id, s.name]));
    const rows = (bookings ?? []).map((b) => ({
      id: b.id,
      customer_name: b.customer_name,
      customer_email: b.customer_email,
      customer_phone: b.customer_phone,
      status: b.status,
      starts_at: b.date_time_start,
      ends_at: b.date_time_end,
      paid_clp: b.final_price,
      class_name: serviceName.get(b.service_id) ?? null
    }));
    if (rows.length === 0) {
      return {
        content: [
          {
            type: "text",
            text: "Sin reservas en el rango. Si esperabas resultados, la cuenta conectada puede no tener permisos de administrador."
          }
        ],
        structuredContent: { bookings: [], count: 0 }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { bookings: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/search-customers.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var search_customers_default = defineTool5({
  name: "search_customers",
  title: "Buscar clientes",
  description: "Busca clientes del CRM por nombre, email o tel\xE9fono. Solo devuelve datos si la cuenta conectada tiene permisos de administrador.",
  inputSchema: {
    query: z4.string().trim().min(2).describe("Texto a buscar en nombre, email o tel\xE9fono."),
    limit: z4.number().int().min(1).max(50).optional().describe("M\xE1ximo de resultados (por defecto 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const term = query.replace(/[%,()]/g, " ").trim();
    const { data, error } = await supabase.from("customers").select("id, name, email, phone, status, created_at").or(`name.ilike.%${term}%,email.ilike.%${term}%,phone.ilike.%${term}%`).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if ((data ?? []).length === 0) {
      return {
        content: [
          {
            type: "text",
            text: "Sin resultados. Si esperabas clientes, la cuenta conectada puede no tener permisos de administrador."
          }
        ],
        structuredContent: { customers: [] }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { customers: data }
    };
  }
});

// src/lib/mcp/tools/get-studio-info.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var get_studio_info_default = defineTool6({
  name: "get_studio_info",
  title: "Informaci\xF3n del estudio",
  description: "Devuelve la base de conocimiento de Nave Studio (metodolog\xEDa, planes, membres\xEDas, reglas, ubicaci\xF3n). Opcionalmente filtra por categor\xEDa.",
  inputSchema: {
    category: z5.string().trim().min(1).optional().describe("Categor\xEDa opcional, por ejemplo 'planes' o 'reglas'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("ai_knowledge").select("category, title, content, priority").eq("is_active", true).order("priority", { ascending: false });
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { knowledge: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pyupvlgdtcxgqjungiof";
var mcp_default = defineMcp({
  name: "studiolanave",
  title: "studiolanave",
  version: "0.1.0",
  instructions: "Herramientas de Nave Studio (Las Condes, Santiago): servicios y precios, horario semanal, cupos disponibles, reservas, clientes del CRM e informaci\xF3n del estudio. Las reservas y clientes requieren una cuenta con permisos de administrador. Zona horaria America/Santiago.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_services_default,
    list_weekly_schedule_default,
    list_available_slots_default,
    list_bookings_default,
    search_customers_default,
    get_studio_info_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
